import Head from 'next/head'
import styles from '../styles/Home.module.css'


import { FileUpload } from 'primereact/fileupload';
 

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>index:: File Uploader </h1>
        <br></br>
        <FileUpload name="fileselected" url="/api/upload"></FileUpload>
      </main>

      <footer className={styles.footer}>Developed by Marshall IT... 06.24.2022</footer>
    </div>
  )
}
