/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.  BLAH

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ca55de7e-7dc0-433d-9067-d51efe4f284e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_92Ll1EJ5H",
    "aws_user_pools_web_client_id": "l7al5bpc16kq1qbngbakm5f7q",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sar-import-bucket145558-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
