import React ,{useState} from 'react';
import AWS from 'aws-sdk'

import Head from 'next/head'
import styles from '../../styles/Home.module.css'


// from: https://javascript.plainenglish.io/how-to-upload-files-to-aws-s3-in-react-591e533d615e

const S3_BUCKET ='YOUR_BUCKET_NAME_HERE';
const REGION ='YOUR_DESIRED_REGION_HERE';


AWS.config.update({
    accessKeyId: process.env.NEXT_PUBLIC_ACCESS_KEY,
    secretAccessKey: process.env.NEXT_PUBLIC_SECRET_KEY,
})

const myBucket = new AWS.S3({
    params: { Bucket: process.env.NEXT_PUBLIC_BUCKET_NAME},
    region: "us-east-1",
})

const UploadAfileTest = () => {

  const [selectedFile, setSelectedFile] = useState(null);

  const handleFileInput = (e) => {
      setSelectedFile(e.target.files[0]);
  }

  const uploadFile = (file) => {

    console.log("process.env.BUCKET_NAME: " + 
    process.env.NEXT_PUBLIC_BUCKET_NAME);

      const params = {
          ACL: "bucket-owner-full-control",
          Body: file,
          Bucket: process.env.NEXT_PUBLIC_BUCKET_NAME,
          Key: file.name
      };

      myBucket.putObject(params)
          .on('httpUploadProgress', (evt) => {
              console.log("File Successfully Uploaded ")
          })
          .send((err) => {
              if (err) console.log("ERROR OCURRED UPLOADING FILE: ", err)
          })
  }


  return <div>

    <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>File Uploader </h1>
            <br></br>
            <input type="file" onChange={handleFileInput}/>
            <br></br>
            <br></br>
            <br></br>
            <button onClick={() => uploadFile(selectedFile)}> Upload to S3</button>
        </main>

        <footer className={styles.footer}>Developed by Marshall IT... 06.24.2022</footer>
    </div>

  </div>

}

export default UploadAfileTest;